module.exports = {
	"SPRITE_ATLAS_FRAME_RIGHT_ARROW": 8,
	"SPRITE_ATLAS_FRAME_LEFT_ARROW": 9,
	"SPRITE_ATLAS_FRAME_LOGO": 10,
	"SPRITE_ATLAS_FRAME_MOBILE": 11,
	"SPRITE_ATLAS_FRAME_TILT_LEFT": 12,
	"SPRITE_ATLAS_FRAME_TILT_RIGHT": 13,
	"SPRITE_ATLAS_ANIM_TILT_RIGHT": 0,
	"SPRITE_ATLAS_ANIM_TILT_LEFT": 1
}